package Apptus.util;

public class DPRQuoteCheck {

    boolean BASKETSNAPSHOT__X_ISNGEM;
    boolean BASKETSNAPSHOT__X_ISNGEMDEVICENEW;

    public DPRQuoteCheck(boolean BASKETSNAPSHOT__X_ISNGEM, boolean BASKETSNAPSHOT__X_ISNGEMDEVICENEW) {
        this.BASKETSNAPSHOT__X_ISNGEM = BASKETSNAPSHOT__X_ISNGEM;
        this.BASKETSNAPSHOT__X_ISNGEMDEVICENEW = BASKETSNAPSHOT__X_ISNGEMDEVICENEW;
    }

    public boolean isBASKETSNAPSHOT__X_ISNGEMDEVICENEW() {
        return BASKETSNAPSHOT__X_ISNGEMDEVICENEW;
    }

    public void setBASKETSNAPSHOT__X_ISNGEMDEVICENEW(boolean BASKETSNAPSHOT__X_ISNGEMDEVICENEW) {
        this.BASKETSNAPSHOT__X_ISNGEMDEVICENEW = BASKETSNAPSHOT__X_ISNGEMDEVICENEW;
    }

    public DPRQuoteCheck(boolean BASKETSNAPSHOT__X_ISNGEM) {
        this.BASKETSNAPSHOT__X_ISNGEM = BASKETSNAPSHOT__X_ISNGEM;
    }
}
