package Apptus.util;

import java.util.ArrayList;
import java.util.List;

public class DPRQuoteL1 {

    boolean DELEGATED_PRICING_REQUEST_ISNEGOTIATED;
    int DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE;
    int DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE;

    public DPRQuoteL1(boolean DELEGATED_PRICING_REQUEST_ISNEGOTIATED, int DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE, int DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE) {
        this.DELEGATED_PRICING_REQUEST_ISNEGOTIATED = DELEGATED_PRICING_REQUEST_ISNEGOTIATED;
        this.DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE = DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE;
        this.DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE = DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE;
    }

    public int getDELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE() {
        return DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE;
    }

    public void setDELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE(int DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE) {
        this.DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE = DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_VALUE;
    }



    public DPRQuoteL1(boolean DELEGATED_PRICING_REQUEST_ISNEGOTIATED, int DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE) {
        this.DELEGATED_PRICING_REQUEST_ISNEGOTIATED = DELEGATED_PRICING_REQUEST_ISNEGOTIATED;
        this.DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE = DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE;
    }

    public boolean isDELEGATED_PRICING_REQUEST_ISNEGOTIATED() {
        return DELEGATED_PRICING_REQUEST_ISNEGOTIATED;
    }

    public void setDELEGATED_PRICING_REQUEST_ISNEGOTIATED(boolean DELEGATED_PRICING_REQUEST_ISNEGOTIATED) {
        this.DELEGATED_PRICING_REQUEST_ISNEGOTIATED = DELEGATED_PRICING_REQUEST_ISNEGOTIATED;
    }

    public int getDELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE() {
        return DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE;
    }

    public void setDELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE(int DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE) {
        this.DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE = DELEGATED_PRICING_REQUEST_TOTAL_DEAL_MONTHLY_MANUAL_VALUE;
    }

    public List<DPRQuotePlanHH> getDPRQuoteL1List(){

        List<DPRQuotePlanHH> DPRQuotePlanHHList = new ArrayList<>();

        DPRQuotePlanHH DPRQuotePlanHH1 = new DPRQuotePlanHH();
        DPRQuotePlanHH1.setBASKETSNAPSHOT__X_PRODUCT_MODULE_NAME("module 1");
        DPRQuotePlanHH1.setBASKETSNAPSHOT__X_QUANTITY(200);
        DPRQuotePlanHH1.setBASKETSNAPSHOT__X_VolumeTier1(10000000);
        DPRQuotePlanHH1.setBASKETSNAPSHOT__X_VolumeTier3(20000000);
        DPRQuotePlanHH1.setBASKETSNAPSHOT__X_VolumeTier2(30000000);
        DPRQuotePlanHH1.setBASKETSNAPSHOT__X_GSTEXCL_TOTAL_RECURRING_CHARGES(1000);

        DPRQuotePlanHH DPRQuotePlanHH2 = new DPRQuotePlanHH();
        DPRQuotePlanHH2.setBASKETSNAPSHOT__X_PRODUCT_MODULE_NAME("module 2");
        DPRQuotePlanHH2.setBASKETSNAPSHOT__X_QUANTITY(300);
        DPRQuotePlanHH2.setBASKETSNAPSHOT__X_VolumeTier1(40000000);
        DPRQuotePlanHH2.setBASKETSNAPSHOT__X_VolumeTier3(50000000);
        DPRQuotePlanHH2.setBASKETSNAPSHOT__X_VolumeTier2(60000000);
        DPRQuotePlanHH2.setBASKETSNAPSHOT__X_GSTEXCL_TOTAL_RECURRING_CHARGES(2000);

        DPRQuotePlanHH DPRQuotePlanHH3 = new DPRQuotePlanHH();
        DPRQuotePlanHH3.setBASKETSNAPSHOT__X_PRODUCT_MODULE_NAME("module 3");
        DPRQuotePlanHH3.setBASKETSNAPSHOT__X_QUANTITY(400);
        DPRQuotePlanHH3.setBASKETSNAPSHOT__X_VolumeTier1(70000000);
        DPRQuotePlanHH3.setBASKETSNAPSHOT__X_VolumeTier3(80000000);
        DPRQuotePlanHH3.setBASKETSNAPSHOT__X_VolumeTier2(90000000);
        DPRQuotePlanHH3.setBASKETSNAPSHOT__X_GSTEXCL_TOTAL_RECURRING_CHARGES(3000);

        DPRQuotePlanHHList.add(DPRQuotePlanHH1);
        DPRQuotePlanHHList.add(DPRQuotePlanHH2);
        DPRQuotePlanHHList.add(DPRQuotePlanHH3);

        return DPRQuotePlanHHList;

    }


}
